[world]
name = "Starkwolf"
description = "A decentralized Werewolf game built with Dojo on Starknet. Players are assigned roles (Werewolf, Villager, etc.) and must strategize to win through voting and nighttime eliminations."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/favsidv/starkwolf"
seed = "starkwolf"

[world.socials]
x = "https://x.com/starkwolf_game"
discord = "https://discord.gg/starkwolf"
github = "https://github.com/your-repo/starkwolf"
telegram = "https://t.me/starkwolf"

[namespace]
default = "starkwolf"

[env]
rpc_url = "http://127.0.0.1:5050/"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"

[writers]
"starkwolf" = ["starkwolf-actions"]